Feature/website_v2/pages/profile
nikhil-g777/openmentorship pull request #128
Opened 2023-07-12 04:05 UTC by helloukey

2023-07-24 19:11 UTC, nikhil-g777 requested changes

2023-07-24 19:11 UTC, nikhil-g777 commented on website_v2/src/helpers/register.ts
Seeing an error when saving the profile. Can you check this
<img width="1077" alt="Screenshot 2023-07-25 at 12 37 44 AM" src="https://github.com/nikhil-g777/openmentorship/assets/6934637/6ff097fb-962a-4561-b40e-d991d4367275">

2023-07-25 11:37 UTC, helloukey commented on website_v2/src/helpers/register.ts
@nikhil-g777 made some changes to the code. Please check if it is working or not.

2023-08-07 20:09 UTC, nikhil-g777 approved these changes

2023-08-07 20:10 UTC, merged