filtered out mentors with active connection
nikhil-g777/openmentorship pull request #186
Opened 2023-09-27 19:20 UTC by helloukey

2023-09-27 19:32 UTC, nikhil-g777 requested changes

2023-09-27 19:32 UTC, nikhil-g777 commented on backend/controllers/matchController.js
> +    const matches = await Match.find({ mentee: _id });
Here you are fetching all matches and then doing an array filter for the active ones, this is not very effective

Let's say you have 100 matches out of which only 5 are active. You're fetching all 100 from the DB so it's not effective. You should be having the status=active filter in the match itself. And from mongoose you can use `.select` to only get the ids.

2023-09-27 19:32 UTC, nikhil-g777 commented on backend/controllers/matchController.js
> +    results = await User.find({ ...filter, _id: { $nin: mentorsId } })
The `_id: { $nin: mentorsId }` should be added to `filter`. Because the filter is used below to get a count of the documents.

The way you have implemented it, the count would be different from the results, leading to inaccurate pagination results.

2023-09-27 19:32 UTC, nikhil-g777 commented on backend/controllers/matchController.js
> +    results = await User.find({ ...filter, _id: { $nin: mentorsId } })
You can just pass the mentorIds array to the `constructExploreFilter` method, which will add the nin to the filter

2023-09-27 19:34 UTC, nikhil-g777 commented on backend/controllers/matchController.js
> +    const matches = await Match.find({ mentee: _id });
* you should have the status=active filter in the DB query itself

2023-09-27 19:56 UTC, helloukey commented
@nikhil-g777,
Made some changes.

2023-09-27 20:09 UTC, nikhil-g777 requested changes

2023-09-27 20:09 UTC, nikhil-g777 commented on backend/controllers/matchController.js
> +    results = await User.find({ ...filter})
Why update this ?

2023-09-27 20:09 UTC, nikhil-g777 commented on backend/controllers/matchController.js
> +    const matches = await Match.find({ mentee: _id, status: 'active' }).select({mentor: 1, _id: 0});
Actually, let's update the `userRecommendations` API as well. So add a helper method called `getActiveMentorIds(menteeId)` and use this in both `searchMentors` and `userRecommendations `

2023-09-27 20:17 UTC, nikhil-g777 commented on backend/controllers/matchController.js
> +    const matches = await Match.find({ mentee: _id, status: 'active' }).select({mentor: 1, _id: 0});
Also, use `constants.matchStatuses.active`

2023-09-28 11:22 UTC, helloukey commented on backend/controllers/matchController.js
> +    const matches = await Match.find({ mentee: _id, status: 'active' }).select({mentor: 1, _id: 0});
@nikhil-g777,
Made those changes, Please check.

2023-09-28 18:52 UTC, nikhil-g777 approved these changes

2023-09-28 18:52 UTC, merged