added careerStatus and userType in profile update
nikhil-g777/openmentorship pull request #191
Opened 2023-09-29 06:11 UTC by helloukey

2023-09-29 06:37 UTC, nikhil-g777 requested changes

2023-09-29 06:37 UTC, nikhil-g777 commented on website_v2/src/components/profileSettings/save_details.tsx
> +    userType,
For now we users don't have the ability to change user type

So, it should not be sent, and the toggle in the profile edit page should be disabled

2023-09-29 06:55 UTC, helloukey commented on website_v2/src/components/profileSettings/save_details.tsx
> +    userType,
@nikhil-g777,
Disabled userType toggle.
Please review.

2023-09-30 16:05 UTC, nikhil-g777 approved these changes

2023-09-30 16:05 UTC, merged