removed api call for post registration
nikhil-g777/openmentorship pull request #195
Opened 2023-09-30 08:33 UTC by helloukey

2023-09-30 21:01 UTC, nikhil-g777 requested changes

2023-09-30 21:01 UTC, nikhil-g777 commented on website_v2/src/components/register/postRegistration/post_registration.tsx
> +    }, 3000);
Can reduce this to 2000? And the transition after clicking "Got it" feels little weird, I think because the first page of the registration flow is flashing. Attached a video on the notion task.

Either remove the timeout here and have a full page loader (or) Keep it as is and remove the registration page flashing

2023-10-01 07:40 UTC, helloukey commented
@nikhil-g777,
Added reset state on the landing page.
I didn't face any screen flash after this fix.
Please check.

2023-10-02 12:21 UTC, nikhil-g777 commented
> @nikhil-g777,
> Added reset state on the landing page.
> I didn't face any screen flash after this fix.
> Please check.

I just checked, and can still see the first register page flash, similar to the previous video I uploaded.

2023-10-02 12:22 UTC, nikhil-g777 commented
Ignore my previous comment, I hadn't pulled the new changes, testing again

2023-10-02 12:25 UTC, nikhil-g777 commented
@helloukey I tested it again after pulling the changes, still seeing the same issue where the first registration page is flashing before the home page opens (like the previous video I uploaded)

2023-10-02 12:47 UTC, helloukey commented
> @helloukey I tested it again after pulling the changes, still seeing the same issue where the first registration page is flashing before the home page opens (like the previous video I uploaded)

I have to look for a different way then.
Working on it.

2023-10-03 18:07 UTC, nikhil-g777 approved these changes

2023-10-03 18:07 UTC, merged