New linkedIn login flow
nikhil-g777/openmentorship pull request #200
Opened 2023-10-04 16:38 UTC by helloukey

2023-10-04 17:26 UTC, nikhil-g777 requested changes
Functionally looks good ! Tested the different statuses and the flow looks so much better

Code wise, there's still some scope to make it cleaner. Some points to keep in mind for the backend : 
-> We are shifting everything to async await, so don't need result objects. We had those earlier when we needed to pass info when chaining promises.
-> Don't need `.exec()` in mongoose. This was used earlier to return promises.

I did push a commit to clean up some of these but I think there is more scope to clean, I'll do it later. In the mean time, added one comment for response status during registration.

2023-10-04 17:26 UTC, nikhil-g777 commented on backend/helpers/user.js
> +      return res.status(401).json({
I think this should be success: true with status code 200 right ?
Because this is the expected flow when a new user is registering

2023-10-04 18:01 UTC, helloukey commented on backend/helpers/user.js
> +      return res.status(401).json({
> I think this should be success: true with status code 200 right ? Because this is the expected flow when a new user is registering

Yeah right!
For registration, I am using only **registrationStatus** and **newUser** from the frontend.
I'll Change the status code to 200 and success to true.

2023-10-08 19:57 UTC, nikhil-g777 approved these changes

2023-10-08 19:57 UTC, merged