Mentor reviews feature
nikhil-g777/openmentorship pull request #224
Opened 2023-10-29 16:21 UTC by helloukey

2023-12-09 12:40 UTC, nikhil-g777 requested changes

2023-12-09 12:40 UTC, nikhil-g777 commented on backend/models/review.js
> +  rating: {
add `required: true` for the `rating` field

2023-12-09 12:40 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +      success: false,
Stick to the new format for API responses, similar to the ones in `UserController`

Each response should have success, errorCode, message

2023-12-09 12:40 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +    // Find by session in reviews and update
I don't think we need to upsert, because once a review is submitted, the user should not be able to edit it. This also adds the risk that a review is overwritten.

Change this to create instead of `findOneAndUpdate`

If an update feature is needed in the future, it should be a separate endpoint.

2023-12-09 12:40 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +const getAllReviews = async (req, res) => {
We will need `get reviews by mentor` and may not need get all reviews. Change this to `getReviews` and take mentorId as an input. Then filter by mentorId.

2023-12-09 12:40 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +    const count = await Review.countDocuments();
After you update this to `get reviews by mentor` based on the above comment, the count needs to be updated so that its the count based on the filter. Refer to `searchMentors` in `userController`

2023-12-20 16:37 UTC, helloukey commented
@nikhil-g777,
Please check if anything is required to change.

2023-12-21 17:46 UTC, nikhil-g777 requested changes

2023-12-21 17:46 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +      success: false,
The other field should be 'message' and not 'error'

2023-12-21 17:46 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +    // Find by session in reviews and update
The variable name can be changed to createdReview instead of updatedReview

2023-12-21 17:46 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +      error: 'please provide all required fields',
Should be 'message' instead of 'error' according to new format we are following. Update throughout this PR

2023-12-21 17:46 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
>        error: 'page and limit needs to be sent',
change to 'message'

2023-12-21 17:46 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
>  // Get all reviews
Update this comment: "Get reviews for a mentor"

2023-12-21 17:46 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +      .skip((page - 1) * limit);
Did you test this, do we not need exec() ?

2023-12-21 17:46 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +      .skip((page - 1) * limit);
You can still populate the session, can be helpful

2023-12-21 17:46 UTC, nikhil-g777 commented on backend/controllers/reviewController.js
> +const getReviews = async (req, res) => {
I'm just seeing the 'getReview' mentor below. Why not combine them to a single method called `getReviews`

It can accept multiple filters like sessionId, mentorId. Rest of the method feels similar. Would be better to combine it into one.

2023-12-21 18:43 UTC, helloukey commented on backend/controllers/reviewController.js
> +      .skip((page - 1) * limit);
> Did you test this, do we not need exec() ?

Yeah, exec() can be used for better stack traces.

2023-12-23 15:12 UTC, nikhil-g777 approved these changes

2023-12-23 15:12 UTC, merged