added matchController condition and helper function for reconnect
nikhil-g777/openmentorship pull request #248
Opened 2023-12-29 20:30 UTC by helloukey

Change-Id: I0690685da41380e2a0f49e32584a1f7d3854679b

2023-12-29 20:30 UTC, helloukey commented
This pull request is part of a stack:
1. added matchController condition and helper function for reconnect ([#248](https://github.com/nikhil-g777/openmentorship/pull/248))
1. cleaned-up updateMatch controller function with helper functions ([#249](https://github.com/nikhil-g777/openmentorship/pull/249))
1. changed redirect to pending tab after reconnect request ([#250](https://github.com/nikhil-g777/openmentorship/pull/250))

2023-12-30 13:25 UTC, nikhil-g777 requested changes

2023-12-30 13:25 UTC, nikhil-g777 commented on backend/helpers/matches.js
> +const reconnectMentor = async (res, body) => {
Update this functions, similar to the changes I mentioned in https://github.com/nikhil-g777/openmentorship/pull/249/files#r1438583478

Add a comment docstring above the functions as well

2023-12-30 13:25 UTC, nikhil-g777 commented on backend/controllers/matchController.js
> +    if(match.status == 'closed' && status == 'active') {
use matchStatuses from `lib/constants.js`. Throughout this PR.

2024-01-02 15:47 UTC, nikhil-g777 approved these changes

2024-01-02 15:50 UTC, merged