registration form validations
nikhil-g777/openmentorship pull request #27
Opened 2020-11-24 21:17 UTC by olessiap

2020-12-04 06:10 UTC, nikhil-g777 requested changes
Please have a look at the comments

2020-12-04 06:10 UTC, nikhil-g777 commented on website/src/pages/Register/RegisterForm.js
> +<<<<<<< HEAD
There seem to be some merge conflicts, can you resolve these

2020-12-04 06:10 UTC, nikhil-g777 commented on website/src/pages/Register/RegisterMain.js
> +
In this page ( Step 1 ), we need all the fields to be required, I am able to click continue without filling any of the fields

2020-12-04 06:10 UTC, nikhil-g777 commented on website/src/pages/Register/RegisterStep2.js
> +        {currentRole === false && (
Not sure what the issue is but I did fill all the fields for work experience but clicking continue doesn't take me to the next page
![Screen Shot 2020-12-04 at 1 04 51 AM](https://user-images.githubusercontent.com/6934637/101128318-5aa0fd80-35cd-11eb-9be3-5fcc87c45909.png)

2020-12-21 07:54 UTC, olessiap commented on website/src/pages/Register/RegisterForm.js
> +<<<<<<< HEAD
heyo, i fixed the merge conflicts, sorry about that!

2020-12-21 07:55 UTC, olessiap commented
hey hey, form validations should be working now! Let me know if I missed anything. Still need to do fix some of the theme styling @nikhil-g777

2020-12-22 08:08 UTC, nikhil-g777 commented
Hey, it looks good for the most part, just a couple of things we might have missed out. 
Can you have a look at this sheet that we spoke about and implement accordingly : https://docs.google.com/document/d/1wxQ4fmbwab5kSOhh5vYQjzjhz7qtqHTYDW0zFAH8mp4

It's alright if it takes longer, lets try doing these and other changes if you have any suggestions

2021-09-02 20:25 UTC, nikhil-g777 approved these changes

2021-09-02 20:25 UTC, nikhil-g777 approved these changes

2021-09-02 20:27 UTC, merged